baseURL = "https://gplusunblocked.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

buildFuture = true
contentDir = "content"
publishDir = "public"

[pagination]
  pagerSize = 5
 
[params]
  contentTypeName = "post"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = false
  homeSubtitle = "Game | Unblocked Games | Classroom 6x "
  description = "Discover how G Plus Unblocked lets you play your favorite browser games anywhere—school, work, or on mobile. Learn access tips, top games, safety advice, and troubleshooting."
  recent_posts_number = 3
  logoText = "G Plus Unblocked"
  logoHomeLink = "/"
  footerLogoText = "G Plus Unblocked"
  googleAnalytics = "UA-XXXXXX-X"

[languages]
  [languages.en]
    title = "G Plus Unblocked"

    [languages.en.params]
      subtitle = "g"
      keywords = "Game | Unblocked Games | Classroom 6x"
      menuMore = "More"
      writtenBy = "by"
      readMore = "Read more"
      readOtherPosts = "More posts"
      newerPosts = "Newer"
      olderPosts = "Older"
      minuteReadingTime = "min read"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"

      [languages.en.params.logo]
        logoText = "G Plus Unblocked"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "My Blog"
        url = "/blog/"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "Archive"
        name = "Archive"
        url = "/archive/"
        weight = 2

      [[languages.en.menu.footer]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

      [[languages.en.menu.footer]]
        identifier = "privacy"
        name = "Privacy"
        url = "/privacy/"
        weight = 2

      [[languages.en.menu.footer]]
        identifier = "contact"
        name = "Contact Us"
        url = "/contact/"
        
        
        weight = 3
